# -*- coding: utf-8 -*-
"""odev1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GqWmOzGrUovsD4uPk4iv3ofiwKm3MqAs
"""

import random as rnd
liste = []

for a in range(3):
  liste2 = []
  for b in range(3):
    i=rnd.randint(1,100)
    liste2.append(i)
  liste.append(liste2)

print (liste)

